version: "3.3"
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./config/nginx/:/etc/nginx/conf.d/
      - ./static/:/django/deliveryNeighbors/static
    depends_on:
      - web
      - redis
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command:
      bash -c "python manage.py makemigrations
      && python manage.py migrate
      && daphne -b 0.0.0.0 -p 8000 config.asgi.prod:application"
#      && python manage.py runserver 0.0.0.0:8000
#      && gunicorn --bind 0.0.0.0:8000 config.wsgi.prod:application --timeout 240"
    ports:
      - "8000:8000"
    expose:
      - "8000"
    env_file:
      - .env
    restart: always
    environment:
      - TZ=Asia/Seoul
  redis:
    image: redis:5
    command: redis-server --port 6379
    ports:
      - "6379:6379"
