# Generated by Django 4.0.4 on 2022-08-09 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_alter_category_category_background_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='cur_latitude',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='cur_longitude',
            field=models.DecimalField(decimal_places=16, max_digits=20, null=True),
        ),
    ]
