# Generated by Django 4.0.4 on 2022-05-20 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='images/avatar/default_img.jpg', upload_to='images/avatar/%Y/%m/%d/'),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
