# Generated by Django 4.0.4 on 2022-08-07 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='https://deliveryneighborsbucket.s3.ap-northeast-2.amazonaws.com/media/avatar/default_img.jpg', null=True, upload_to=''),
        ),
    ]
