# Generated by Django 4.0.4 on 2022-08-08 23:53

from django.db import migrations, models
import storages.backends.s3boto3


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='media/avatar/default_img.jpg', storage=storages.backends.s3boto3.S3Boto3Storage, upload_to='media/avatar/'),
        ),
    ]
